### ISSUE TITLE
Cancel the notification once charger is plugged

### ISSUE THREAD

**Issue by mizzunet** [electrickite/batsignal#14]
It would be nice to cancel/dismiss the low battery (15%) notification, which is critical, once the charge is plugged in.

Don't you think?

**Comment by electrickite** [comment]
Closing existing notifications would require keeping a reference to each notification as it is created. We would also probably need to handle close events in order to keep the notification references current. This would add a fair amount of complexity to the notification handling.

I would review a PR for this feature, but it would need to introduce as few dependencies as possible.

**Comment by arnavgr** [comment]
is there any way to make it disappear after a certain time? i use dunst and i have time limit on notifications which does not apply to batsignal notifications.

**Comment by electrickite** [comment]
@arnavgr The `-e` option causes notifications to be creates with the expiration flag set,

**Comment by arnavgr** [comment]
do i have to write the number of seconds after which it expires or does it expire on its own?

**Comment by electrickite** [comment]
`-e` accepts no options - it sets notifications to the libnotify default timeout value.

**Comment by uti5** [comment]
I don't know if this is relevant, but notify-send has `-p` and `-r ID` for printing an ID and replacing a notification, so if a critical notification was issued with `notify-send -p -u critical 'this is critical'`, one can later do `notify-send -r ID 'problem solved'` to replace and remove it (if non-critical notifications are set to expire).

**Comment by hseg** [comment]
A cursory search regarding this shows this is directly supported by `libnotify`
https://gnome.pages.gitlab.gnome.org/libnotify/method.Notification.close.html
so this should be doable with no added dependencies. Moreover, given
https://gnome.pages.gitlab.gnome.org/libnotify/method.Notification.update.html
exists, it appears we can get away with just maintaining a single notification
object that gets updated as needed, and `close/show`'d as necessary (this would
suggest the naming is unnecessarily confusing, but _shrugs_)

**Comment by electrickite** [comment]
Thanks to @Nikl174 for the PR addressing this issue and to @hseg for reviewing the libnotify docs!
