### ISSUE TITLE
Notification on critical battery level does not expire

### ISSUE THREAD

**Issue by jpmvferreira** [electrickite/batsignal#15]
I'm running batsignal from the AUR on i3WM, where the relevant configuration section reads
```
exec --no-startup-id /usr/bin/batsignal -b -w 10 -c 7 -d 5 -W "Warning" -C "Warning" -D "/usr/bin/systemctl hibernate" -m 15 -e
```

Still, when faced with the critical battery level notification, it doesn't seem to expire, unlike the battery warning level which behaves as expected.

I'll run batsignal from my terminal tomorrow and provide the output when the battery reaches each battery level.

**Comment by electrickite** [comment]
Most notifications generated by batsignal have their urgency set to `Normal`, however the critical battery level notifications use `Critical` urgency. Notification servers can display the various urgency levels differently, although the spec suggests that critical notifications should not automatically expire. 

https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#urgency-levels 

Do you use dunst as your notification server by any chance? I believe it defaults to displaying critical urgency without a timeout.

**Comment by jpmvferreira** [comment]
Yes I am using dunst, checking my config file reveals that critical notifications do not expiry.

You're the first person (or program) that I've used which actually makes use of the urgency levels, which isn't a complaint, quite the opposite, it's just that I was used to the fact that everybody stuck with the normal urgency level, so I didn't even thought about the possibility that there could be something else causing the non expiration besides batsignal.

Thanks for the help, I'll be closing this issue.
