### ISSUE TITLE
Could not read /sys/class/power_supply/hidpp_battery_0/charge_now

### ISSUE THREAD

**Issue by kurkii** [electrickite/batsignal#17]
Whenever I run `batsignal` I get this error message:
```
Using batteries: BAT1, hidpp_battery_0
batsignal: Could not read /sys/class/power_supply/hidpp_battery_0/charge_now: No such file or directory
```

I am pretty sure BAT1 is my laptop battery and hidpp_battery_0 is my mouse battery, is there a way I can only use BAT1?

**Comment by kurkii** [comment]
Nevermind, found the answer in the man page immediately after lol,
use flag -i to ignore missing battery errors

**Comment by electrickite** [comment]
You should be able to specify the battery to use with the `-n` option: `-n BAT1`
