### ISSUE TITLE
Wrong MANPREFIX

### ISSUE THREAD

**Issue by tibequadorian** [electrickite/batsignal#18]
From [TLDP](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/usr.html):

>/usr/man
>It once held the man pages. It has been moved to /usr/share/man.

**Comment by electrickite** [comment]
If you are installing to `/usr` rather than the default `/usr/local` then you will need to set both `PREFIX` and `MANPREFIX` :

    PREFIX=/usr MANPREFIX=/usr/share/man make

The [FHS 3](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) places man pages in the `/usr/local` hierarchy in `/usr/local/man` which is why the default variables are configured this way.

**Comment by tibequadorian** [comment]
Point 4.9.4 of the [FHS 3](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) also says about `/usr/local/share`
>The requirements for the contents of this directory are the same as for /usr/share.

and places man pages in `/usr/share/man` according to [point 4.11.2](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html).

So there is nothing wrong with setting `MANPREFIX=$(PREFIX)/share/man`.

**Comment by electrickite** [comment]
Not that I want to get into an argument over specifications, but different distributions interpret that particular discrepancy in different ways. My interpretation, (and the Arch family of distros) place `/usr/local` man pages in `/usr/local/man`. All distributions that I am aware of also symlink these two directories to each other, but I'd rather follow the spec.

In any event, the Makefile in version 1.3.5 includes a bit of logic to set `MANPREFIX` correctly based on `PREFIX` so there should be no need to manually override it any longer. You also have the option of specifying `MANPREFIX` during install if you need a different path.
