### ISSUE TITLE
batsignal.service does not exist

### ISSUE THREAD

**Issue by arnavgr** [electrickite/batsignal#19]
i installed this on arch i3wm through aur. After installing systemctl enable batsignal gives result `Failed to start batsignal.service: Unit batsignal.service not found.
`      

what am i supposed to do?

**Comment by electrickite** [comment]
Batsignal is installed as a user service - you need to use the `--user` systemctl flag:

    $ systemctl --user enable batsignal.service

**Comment by arnavgr** [comment]
i get the same error using that command

**Comment by arnavgr** [comment]
one last question where is the config file of batsignal located in?

**Comment by electrickite** [comment]
If the user service is not recognized after installing the AUR package you may need to run (note without sudo)

    $ systemctl —user daemon-reload

You should not need to run the `batsignal` command manually if you are using the  systemd service. 

Regarding your second question, batsignal does not have a configuration file, all options are passed as arguments and are documented in the man page. For a full battery notification at 97% charge for example, you would use:

    $ batsignal -f 97

If you want to use custom options for the user service that is installed with the AUR package, you can either create your own copy of the service file in `~/.config/systemd/user` or use systemd drop-in directory overrides to adjust only the ExecStart command. 

https://wiki.archlinux.org/title/Systemd#Drop-in_files

**Comment by arnavgr** [comment]
after i run batsignal -f 97 will it give notification everytime(even after restarting) or do i have to add it to my i3 config so that it runs at startup

**Comment by electrickite** [comment]
You will either need to add it to your i3 startup, enable the systemd user service, or start it another way on login.

**Comment by electrickite** [comment]
Could be related to the polling interval behavior - it never supported the "full" level very well in certain circumstances. Give version 1.4.0 a try and see if that works any better.

**Comment by arnavgr** [comment]
it isnt working. should i edit the batsignal.c file in my yay? will it change anything?

**Comment by electrickite** [comment]
Are you using version 1.4.0? What is the output of 

    $ batsignal -v

**Comment by arnavgr** [comment]
batsignal 1.4.0 is the output

**Comment by arnavgr** [comment]
batsignal -f 97 only shows using batteries in the terminal when i am at 97

**Comment by electrickite** [comment]
You are free to file a new issue if you'd like. I cannot reproduce this behavior on version 1.4.0. For example, running:

    $ batsignal -f 96

causes a full message to be displayed when the battery reaches 96% or shortly after.

Regarding the other question about removing notifications, it has been discussed before but would require tracking all messages sent via libnotify. I would likely accept a pull request for this feature, but so far there has been no movement on it.

**Comment by arnavgr** [comment]
okay so setting batsignal -f to any number gives any notification. i am using dunst as notification manager so it shouldnt be a problem . should i clone the repo , edit batsignal.c and then install?

**Comment by electrickite** [comment]
I'm not sure what you mean by "clone the repo , edit batsignal.c and then install", but feel free to open an issue if you track down the problem.

Out of curiosity, how many batteries do you have in your system? What do you see if you run 

    $ ls /sys/class/power_supply

**Comment by arnavgr** [comment]
### AC0 and BAT0 are my batteries(idk why i have 2 when i use 1 laptop)

 i mean should i clone your batsignal repo(git clone https://github.com/electrickite/batsignal.git) and edit its config file and then 

```
make
sudo make install
```

**Comment by electrickite** [comment]
> I mean should i clone your batsignal repo(git clone https://github.com/electrickite/batsignal.git) and edit its config

There is no config file, but sure you can edit the source code and build the project yourself if that works for you. If you find something that works let me know - maybe we can figure out what the issue is by looking at what you changed.

**Comment by arnavgr** [comment]
i changed battery full to 100 wherever it was 0 and compiled it. didnt work. i guess ill live with it not that big of a deal

**Comment by arnavgr** [comment]
UPDATE: I found one more problem. the warning danger and normal notifications of battery low are the same. the danger level doesnt show a red notfication (which i have set in dunst)

**Comment by arnavgr** [comment]
UPDATE: I MADE IT WORK now it shows notification when its full
