### ISSUE TITLE
Fails if BAT0 does not exist

### ISSUE THREAD

**Issue by yochananmarqos** [electrickite/batsignal#2]
```
batsignal: Could not open /sys/class/power_supply/BAT0/status: No such file or directory
```

```
$ ls /sys/class/power_supply
ACAD  BAT1  hidpp_battery_0
```

`batsignal` 1.0.0-1
Manjaro GNOME
Dell Inspiron 5575

**Comment by electrickite** [comment]
The `-n` option can be used to specify a battery device name. Ex:

`$ batsignal -n BAT1`

See `man batsignal` for the full list of options.

**Comment by yochananmarqos** [comment]
I peeked at the man page, but missed that. Thanks for the quick reply!
