### ISSUE TITLE
Send test notification

### ISSUE THREAD

**Issue by ldelossa** [electrickite/batsignal#20]
Hey, 

Currently, is there a way to send a test notification with batsignal? Basically, I wanted to confirm it would work with my specific notification daemon. I tried with -o but that didnt create a message. 

Instead, I just set the warning level above where my battery was currently at and started batsignal. 

Is there a way to just send a test? If not, would you accept a PR for this? Id be interested in implementing.

**Comment by electrickite** [comment]
The -o option should send notifications if the battery charge is within one of the levels you set. You could test with 

    $ batsignal -o -w 100

**Comment by ldelossa** [comment]
Thank you that works :) Maybe worth a mention somewhere in docs. 

Also thanks for this, the other bat daemons crash on me all the damn time, yours has been rock solid.
