### ISSUE TITLE
Makefile overwritting CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by motorto** [electrickite/batsignal#21]
Is it possible to rewrite the makefile in a way that the user CFLAGS and LDFLAGS are not overwritten ? And don't overwrite CC

Trying to update the package on void but can't cross compile because of the overwritten flags.

**Comment by electrickite** [comment]
Version 1.5.1 updates the Makefile to preserve CFLAGS, LDFLAGS, and CC. It does do a little dancing around CC in particular. On some systems CC defaults to c99, which will not accept the C11 standard option.

These variables can also all be overridden on the command line as options to make if needed.

**Comment by electrickite** [comment]
Closing after updates to the Makefile, but feel free to re-open if needed.

**Comment by motorto** [comment]
The Makefile as it is now is able to correctly preserve the envs from the system. Thanks packaged 1.5.1 to voidLinux
