### ISSUE TITLE
Could not open /sys/class/power_supply/BAT0/status

### ISSUE THREAD

**Issue by mcdylanb** [electrickite/batsignal#3]
Tried to test batsignal while my battery level was 15

I ran this command:
`batsignal -c 10`

returns this error:
`batsignal: Could not open /sys/class/power_supply/BAT0/status: No such file or directory`

I have notice I have a different file structure for my power_supply
|
+---- power_supply
      +---ACAD
       |
       \ BAT1

is there a possible way to change where it points?

**Comment by electrickite** [comment]
What is the batsignal version? 

    batsignal -v

**Comment by mcdylanb** [comment]
somehow
`batsignal 1.0.0`

installed at the AUR

**Comment by electrickite** [comment]
If you update to 1.1.1-1 (the current version in the AUR) your battery should be automatically detected if possible. You can also use the `-n` option to set the battery name. Ex:

    batsignal -n BAT1

**Comment by mcdylanb** [comment]
gosh im that stupid

Updated to 1.1.1
works like a charm

thank you fam!
