### ISSUE TITLE
Feature request: add option to show message when charging and discharging

### ISSUE THREAD

**Issue by harishnkr** [electrickite/batsignal#31]
Is it possible to add flags where certain messages can be shown while battery charging is removed or when battery starts charging? Maybe read from /sys/class/power_supply/BAT0/status and send messages accordingly? Sorry if this feature is already implemented or if there are alternative methods for this.

**Comment by electrickite** [comment]
Charging/discharging notifications are now supported in version 1.8.0 with the `-p` option.

**Comment by harishnkr** [comment]
Thanks

**Comment by harishnkr** [comment]
Just want to point out that although the new update works perfectly, there are other states than "charging" and "discharging". There is a state called "not charging" where the power cord is plugged but it does not automatically charge because the battery level is near full. I am personally satisfied with this feature and am not sure entirely how to tackle this particular situation but in case there are changes happening in this direction, my opinions to tackle this problem could be either of these:


- Leave it as is, so the message for discharging and charging only when the system charges the battery
- Add "charging" and  "not charging" status as part of "plugged in" and "discharging" as "plug removed" (or any other similar message)
- Send the message for charging even though it is plugged in but not charging (during state "not charging")
