### ISSUE TITLE
Limit the amount of notifications for battery full state to one, once the battery is at the full level

### ISSUE THREAD

**Issue by izmyname** [electrickite/batsignal#35]
I've configured batsignal via systemd-override service.

```
[Service]
ExecStart=
ExecStart=batsignal -m 5 -I battery -n BAT1 -p  -f 100 -w 30 -c 15 -d 5 -D systemctl poweroff
```

Everything works good, but when the battery level reaches full state - batsignal just keeps spamming 'battery is full' notification shortly, after I dismiss the previous one. It would be nice to have an option to limit the amount of notifications for the full state to one, regardless of the timeout set - similar to how 'warning',  'critical', 'charging' and 'discharging' notifications behave.

**Comment by Bootjewolf** [comment]
I am having the same problem and was wondering why this issue was closed. Am I missing something in the configuration or is this something that could be added to batsignal as a new feature. If I have some time I would love to look into it.
