### ISSUE TITLE
-D flag ran command ?

### ISSUE THREAD

**Issue by motorto** [electrickite/batsignal#8]
Don't know if its an issue with batsignal or not but is possible that with the -D flag run a command with a space ?

What I want to do is run the following command sudo ZZZ (hibernate the system) 

I tried : 

> batsignal -D "sudo ZZZ" -b
> batsignal -D 'sudo ZZZ' -b
> batsignal -D sudo ZZZ -b

But none seem to work ...

**Comment by electrickite** [comment]
What happens when the command is run? Try without the `-b` flag. You could also try replacing the command with something else to test, like `-D “touch /tmp/testfile”` to see if that works.

**Comment by motorto** [comment]
I tried without the b flag and it works ! Maybe something with
daemonizing the programm ?

**Comment by electrickite** [comment]
My guess would be the issue is with the sudo call in your command. Since the program forks to run in the background with the `-b` flag, perhaps sudo does not work in the new process.

**Comment by motorto** [comment]
That doesn't seem to be it.

I tried on my xinitrc :
batsignal -D touch ~/a -b

And it didn't create the file when reached the danger level , but
running as 
batsignal -D touch ~/a & 

Seems to work , nevertheless I can close the issue , running as stated
above works , and thats fine by me.

**Comment by zaggash** [comment]
I also have a problem with the -D argument.
I run it with -b also.

I try to execute "systemctl suspend" (no sudo), but it never suspends.
No output when I redirect the program to /tmp/bat.log 2>&1

I'm using bspwm and starting batsignal from bspwmrc

**Comment by motorto** [comment]
Glad I am not the only one having issue, I think the -D argument only
runs if the batsignal is launched from an open terminal. 

If I then put the same command on my xinitrc , it doesn't work .

**Comment by electrickite** [comment]
That may be the case. Right now, batsignal uses the `system()` call to run the -D command, which should just pass the string directly to `/bin/sh -c` to execute. Maybe string itself is not surviving the fork... I will look in to that as a solution or perhaps at switching to the exec family of functions.

**Comment by electrickite** [comment]
@motorto  I am having trouble reproducing this behavior. Using version 1.1.2, the danger command works as expected with and without the `-b` flag. See below:

```
$ ./batsignal -v
batsignal 1.1.2
$ ls
batsignal  batsignal.1  LICENSE  main.c  main.o  Makefile  README.md  test  version.h
$ ./batsignal -w 99 -c 98 -d 97 -D "touch testfile"
Using battery: cw2015-battery
^C
$ ls
batsignal  batsignal.1  LICENSE  main.c  main.o  Makefile  README.md  test  testfile  version.h
$ rm testfile 
$ ./batsignal -b -w 99 -c 98 -d 97 -D "touch testfile"
Using battery: cw2015-battery
$ ls
batsignal  batsignal.1  LICENSE  main.c  main.o  Makefile  README.md  test  testfile  version.h
```

**Comment by motorto** [comment]
@electrickite  Yeah you seem to be right running the command as you did seems to work. But running with -b after the D option doesn't can you confirm that ?  

> batsignal -b -w 99 -c 98 -d 97 -D "touch testfile" (this works)
> batsignal -w 99 -c 98 -d 97 -D "touch testfile" -b (this doesn't work)

**Comment by electrickite** [comment]
@motorto Both commands work for me. The placement of the -b flag does not seem to matter.

**Comment by motorto** [comment]
@electrickite  
hum that's weird did a quick test on my xinitrc with -b after and it works ... Now I feel stupid , for wasting your time ... Sorry ! 

@zaggash 
Could you please try and see if it's working for you too ?

> batsignal -D "systemctl suspend" -b

**Comment by zaggash** [comment]
Here what I had on my machine 

```
$ batsignal -v
batsignal 1.1.2
```

```
# Start Battery Monitor
batsignal -b -W 'Battery level is running low' \
  -c '7' -C 'Low Battery, charge the Battery Now !' \
  -d '5' -D 'systemctl suspend' \
  -n 'BAT0'
```

I'll test a simpler one like the one you tested and share the results.

**Comment by zaggash** [comment]
Here are the results:

`batsignal -b -w 99 -c 98 -d 97 -D 'touch /tmp/battestfile'`
This created the file

`batsignal -b -w 99 -c 98 -d 94 -D 'touch /tmp/battestfile' -n BAT0`
This one didn't create the file

**Comment by electrickite** [comment]
I appreciate the examples, but I am still unable to reproduce the issue locally. One thing to keep in mind: it could take up to 60 seconds to register that the battery level has dropped below the danger threshold, so checkging too soon would give these kinds of intermittent results.

The command option parsing is using standard `getopt()` from `unistd.h`, so the order of arguments should not matter.

**Comment by zaggash** [comment]
I let the command run way below the treshold.

When the command is running, the process is shown without any brackets, not sure if it is important.

If it is working for me with -n before -D, I'll work with that.
I do not have another reproducer to share.

**Comment by zaggash** [comment]
So I assume there is a problem with the command I try to run "systemctl suspend"
`batsignal` doesn't execute it or doesn't have permission.
I do not have logs tho.

I tried with a simple touch command and it is working on every case scenario.
